### ISSUE TITLE
App crashing on Nexus 4: illegal UTF-8 character

### ISSUE THREAD

**Issue by rustema** [rustema/peggy-meter#1]
I/PeggiMeter.DataCtrl(17938): Logging user
W/BiChannelGoogleApi(17938): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms
F/art     (17938): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: **input is not valid Modified UTF-8: illegal start byte 0xf0**
F/art     (17938): art/runtime/check_jni.cc:65]     string: '📈'
F/art     (17938): art/runtime/check_jni.cc:65]     in call to NewStringUTF
F/art     (17938): art/runtime/check_jni.cc:65]     from java.lang.String android.content.res.StringBlock.nativeGetString(long, int)
F/art     (17938): art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
F/art     (17938): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x72b7b000 self=0xb88dd408
F/art     (17938): art/runtime/check_jni.cc:65]   | sysTid=17938 nice=0 cgrp=default sched=0/0 handle=0xb6f70bec
F/art     (17938): art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=215 stm=18 core=1 HZ=100
F/art     (17938): art/runtime/check_jni.cc:65]   | stack=0xbe546000-0xbe548000 stackSize=8MB
F/art     (17938): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #00 pc 00004e64  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #01 pc 00003665  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #02 pc 00256401  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #03 pc 00238fbf  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+158)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #04 pc 000b199b  /system/lib/libart.so (art::JniAbort(char const*, char const*)+610)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #05 pc 000b20d5  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #06 pc 000b468f  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.129)+922)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #07 pc 000be1bd  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+44)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #08 pc 00089e1f  /system/lib/libandroid_runtime.so (???)
F/art     (17938): art/runtime/check_jni.cc:65]   native: #09 pc 00263393  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_content_res_StringBlock_nativeGetString__JI+102)
F/art     (17938): art/runtime/check_jni.cc:65]   at android.content.res.StringBlock.nativeGetString(Native method)
F/art     (17938): art/runtime/check_jni.cc:65]   at android.content.res.StringBlock.get(StringBlock.java:82)
F/art     (17938): art/runtime/check_jni.cc:65]   - locked <0x202f8b8b> (a android.content.res.StringBlock)

**Comment by demetrNieA** [comment]
Не все смайлы одинаково полезны ;-)

**Comment by rustema** [comment]
что верно - то верно...

**Comment by rustema** [comment]
Duplicate of #9
