### ISSUE TITLE
Android app crashes immediately.

### ISSUE THREAD

**Issue by JamieABall** [rustema/peggy-meter#23]
Run the app and it will get as far as putting up the welcome screen and then crashes.

**Comment by rustema** [comment]
Crashes should go away after downloading google-services.json from Firebase and placing it in https://github.com/rustema/peggy-meter/blob/master/.gitignore#L3-L4

**Comment by rustema** [comment]
@JamieABall can you update this please?

**Comment by JamieABall** [comment]
The issue is fixed as described above.
