### ISSUE TITLE
Missing Emoji on physical Alcatel Onetouch 4

### ISSUE THREAD

**Issue by ryankwok** [rustema/peggy-meter#9]
[Screenshot](https://imgur.com/a/dWLlMrW)(Private Link)

Also note that there are no corresponding emojis in the graph either.
This is not an issue for the emulated Nexus 5X that I've been testing on.

**Comment by rustema** [comment]
Yep, that's the downside of using UTF-8 characters for smileys.
A fix would be creating proper image assets (icons) and using them on something like image buttons.

**Comment by rustema** [comment]
Saketh will be looking into this.
